# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageUtil.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageUtil.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11MessageUtil.proto\"B\n\nMessageBox\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x11\n\ttrans_str\x18\x02 \x03(\t\x12\x13\n\x0btrans_photo\x18\x03 \x03(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGEBOX = _descriptor.Descriptor(
  name='MessageBox',
  full_name='MessageBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MessageBox.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trans_str', full_name='MessageBox.trans_str', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trans_photo', full_name='MessageBox.trans_photo', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['MessageBox'] = _MESSAGEBOX

MessageBox = _reflection.GeneratedProtocolMessageType('MessageBox', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBOX,
  __module__ = 'MessageUtil_pb2'
  # @@protoc_insertion_point(class_scope:MessageBox)
  ))
_sym_db.RegisterMessage(MessageBox)


# @@protoc_insertion_point(module_scope)
